### ISSUE TITLE
Deciding on what the Agency is about.

### ISSUE THREAD

**Issue by elenamarinaki** [fac22/Michael-Elena-Agency#2]
Hi Michael,

I was thinking about the theme of our agency. I thought maybe we could make it a hire robot aganecy. We could provide our customers with robots of their choice, depending on their everyday needs.

What do you think about it?

**Comment by MJOW1999** [comment]
Hi Elena,

That sounds like a really cool idea. What types of robots do you have in mind?

**Comment by elenamarinaki** [comment]
It can be anything really. Like robots for home chores, like cleaning, washing etc, to companion robots, or robots with certain specific skills. For example, you could hire a photographer robot to take pictures of your event. Or anything else we can imagine :)

**Comment by elenamarinaki** [comment]
Please, check also the pull request :)

**Comment by MJOW1999** [comment]
Okay, I like that idea. Shall we narrow it down to how many robots we want? I was thinking around 4 - 6 different robots would be the sweet spot

**Comment by elenamarinaki** [comment]
Sounds perfect!

**Comment by MJOW1999** [comment]
Cool, that's sorted then
