### ISSUE TITLE
Agency name + characters

### ISSUE THREAD

**Issue by elenamarinaki** [fac22/Michael-Elena-Agency#4]
Hi Michael,

so I was trying to think of a name of our agency. The only one I thought so far is `ME Robotics` (from our initials 🤣🤣🤣)

Also, I was thinking about the **characters** in our team:

* robot 1: home-assistant -> helps with everyday inside chores, cooking, tyding up, fixing home malfunctions
* robot 2: scheduler -> the modern solution to balance personal and work life!
* robot 3: shopping-assistant -> personal or owned by up to 3 different households, helps with everyday shopping needs
* robot 4: visual-helper -> helps people with impaired eyesight in various activities, like reading, navigating the city etc
* robot 5: the doctor -> again, personal or owned by up to 3 different households, helps diagnosing medical issues and with communication, booking etc between you and your GP
* robot 6: the entertainer -> for amusement purposes, parties, events, etc

What do you think?

**Comment by elenamarinaki** [comment]
ooops I just saw you have already MEA Robotics!! Perfect!! 😄

**Comment by MJOW1999** [comment]
Seems we were on a similar wavelength with the name 😂😂.

I like the concepts for the robots. I was thinking we could give them names, similar to how Alexa is.

The only problem is I can't think of any names 😅

**Comment by elenamarinaki** [comment]
Hahaha yes indeed! 😆😆😆

Yes, giving them names is cool!! Don't worry, let me do the sections first and I am sure we will get inspired sooner or later! 🤞

**Comment by MJOW1999** [comment]
I have a few ideas for the names now 💡

I was thinking of having alliteration for the names and roles. For example, Herbie the Home Helper.

**Comment by elenamarinaki** [comment]
😊 This is cool, I love the name Herbie! Yes, let's do that!

**Comment by MJOW1999** [comment]
Cool, I'll come up with some names!
